name: Release Workflow

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Bump version to the release tag
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          echo "Bumping application version to $TAG_NAME"
          mvn --no-transfer-progress versions:set -DnewVersion=$TAG_NAME
          mvn --no-transfer-progress versions:commit
          mvn --no-transfer-progress clean package -DskipTests

      - name: Commit changes to pom.xml and push to main
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR_ID+$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "generated"
          git push

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          echo "Building Docker image with tag $TAG_NAME"
          docker build -t nzuwera/url-shortner:$TAG_NAME -t nzuwera/url-shortner:latest .

      - name: Push Docker image
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          echo "Pushing Docker image to Docker Hub with tag $TAG_NAME"
          docker push nzuwera/url-shortner:$TAG_NAME
          docker push nzuwera/url-shortner:latest
