name: Release Workflow

on:
  release:
    types: [published]

jobs:
  release:
    if: startsWith(github.event.release.tag_name, 'v')
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      # Update the version in build.gradle
      - name: Bump version to the release tag
        env:
          USER_NAME: "${{ env.GITHUB_ACTOR }}"
          USER_EMAIL: "${{ env.GITHUB_ACTOR }}@users.noreply.github.com"
          USER_COMMIT_MESSAGE: "Release version update"

        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          echo "Bumping application version to $TAG_NAME"
          sed -i "s/version = '.*'/version = '$TAG_NAME'/" build.gradle
          chmod +x gradlew
          ./gradlew clean build -x test

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build Docker image
      - name: Build Docker image
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          echo "Building Docker image with tag $TAG_NAME"
          docker build -t nzuwera/url-shortner:$TAG_NAME -t nzuwera/url-shortner:latest .

      # Push Docker image
      - name: Push Docker image
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          echo "Pushing Docker image to Docker Hub with tag $TAG_NAME"
          docker push nzuwera/url-shortner:$TAG_NAME
          docker push nzuwera/url-shortner:latest

      - name: Push new version to main branch
        env:
          USER_NAME: "${{ env.GITHUB_ACTOR }}"
          USER_EMAIL: "${{ env.GITHUB_ACTOR }}@users.noreply.github.com"
          USER_COMMIT_MESSAGE: "Release version update"
        run: |
          git config --global user.name "${{ env.USER_NAME }}"
          git config --global user.email "${{ env.USER_EMAIL }}"
          git commit -a -m "${{ env.USER_COMMIT_MESSAGE }}"
          git push