name: Release Workflow

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Bump version to the release tag
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          echo "Bumping application version to $TAG_NAME"
          mvn --no-transfer-progress versions:set -DnewVersion=$TAG_NAME
          mvn --no-transfer-progress versions:commit
          mvn --no-transfer-progress clean package -DskipTests
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          echo "Building Docker image with tag $TAG_NAME"
          docker build -t nzuwera/url-shortner:$TAG_NAME -t nzuwera/url-shortner:latest .
      - name: Push Docker image
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          echo "Pushing Docker image to Docker Hub with tag $TAG_NAME"
          docker push nzuwera/url-shortner:$TAG_NAME
          docker push nzuwera/url-shortner:latest

      - name: Configure Git user
        run: |
            git config --global user.name "${{ github.actor }}"
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit version bump
        run: |
            TAG_NAME=${{ github.event.release.tag_name }}
            git add pom.xml
            git commit -m "Bump version to $TAG_NAME"
            git push origin main  # Change this if your default branch is not 'main'

